# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: rails_blog_development

test:
  <<: *default
  database: rails_blog_test

#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# If the connection URL is provided in the special DATABASE_URL environment
# variable, Rails will automatically merge its configuration values on top of
# the values provided in this file. Alternatively, you can specify a connection
# URL environment variable explicitly:
#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# Connection URLs for non-primary databases can also be configured using
# environment variables. The variable name is formed by concatenating the
# connection name with `_DATABASE_URL`. For example:
#
#   CACHE_DATABASE_URL="postgres://cacheuser:cachepass@localhost/cachedatabase"
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  primary: &primary_production
    <<: *default
    database: rails_blog_production
    username: rails_blog
    password: <%= ENV["RAILS_BLOG_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: rails_blog_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rails_blog_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: rails_blog_production_cable
    migrations_paths: db/cable_migrate
